name=RVLArduinoWiFi
version=1.0.0
author=Bryan Hughes <bryan@nebri.us>
maintainer=Bryan Hughes <bryan@nebri.us>
sentence=An implementation of RVL based on the Arduino framework
paragraph=For more information, visit https://github.com/rvl-system/rvl-arduino-wifi
category=Communication
url=https://github.com/rvl-system/rvl-arduino-wifi
architectures=esp8266,esp32
